version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
      args:
        NEXT_PUBLIC_API_URL: https://api.flower.bayburt.lu
        NEXT_PUBLIC_APP_URL: https://flower.bayburt.lu
    restart: unless-stopped
    expose:
      - "3001"
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      PORT: 3001
      HOST: 0.0.0.0
      LOG_LEVEL: ${LOG_LEVEL:-info}
      CORS_ORIGIN: ${CORS_ORIGIN:-https://flower.bayburt.lu}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
    networks:
      - flower_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
      args:
        NEXT_PUBLIC_API_URL: https://api.flower.bayburt.lu
        NEXT_PUBLIC_APP_URL: https://flower.bayburt.lu
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: https://api.flower.bayburt.lu
      NEXT_PUBLIC_APP_URL: https://flower.bayburt.lu
    depends_on:
      - api
    networks:
      - flower_network

networks:
  flower_network:
    driver: bridge